Decoder.
JetBrains-Research/graph-code-nets pull request #5
Opened 2022-04-15 14:40 UTC by timav566

Decoder and training and validation steps were implemented.

P.S. run "train_model_test" to see the results.

2022-04-25 15:51 UTC, egor-bogomolov requested changes
Good job! There are no type annotations at the moment, please add them (both for arguments and for return values). Also, there are several issues with the model implementation that should be fixed before merging.

I did not check notebooks for now, will do so after fixes to the scripts.

2022-04-25 15:51 UTC, egor-bogomolov commented on running/util.py
> +def positional_encoding(dim, sentence_length, dtype=torch.float32):
It is better not to use constant tensors in your models without wrapping them into Parameter or registering them as buffers. Things to consider are:
1. Should the tensor update during training (does it require gradient)? -- `Parameter(...)`
2. Should user see it alongside model parameters? -- Rare case when you really want it to be among the parameters but do not need to update it -- `Parameter(..., requires_grad=False)`
3. Ok, not among the parameters, but belongs to the models' state and should be together with weights when dumping the model into a checkpoint file -- `self.register_buffer("tensor_name", tensor_name)`
4. Well, it's something big that I don't want to store in the checkpoint, but it still should be transferred to GPU/CPU/multiple GPUs in distributed training/... -- `self.register_buffer("tensor_name", tensor_name, persistent=False)`

Also Autograd will have more information about it and can work with it more efficiently.


In this specific case when you have some non-trivial code to compute tensor values + know how it will be applied, it is better to turn positional encoding into a separate module while registering the values as buffer (see [here](https://pytorch.org/tutorials/beginner/transformer_tutorial.html) for example).

2022-04-25 15:51 UTC, egor-bogomolov commented on running/util.py
> +def positional_encoding(dim, sentence_length, dtype=torch.float32):
[A really good thread explaining different use-cases](https://discuss.pytorch.org/t/what-is-the-difference-between-register-buffer-and-register-parameter-of-nn-module/32723)

2022-04-25 15:51 UTC, egor-bogomolov commented on running/util.py
> +def prefix_sum(arr):
[Use built-ins](https://pytorch.org/docs/stable/generated/torch.cumsum.html)

2022-04-25 15:51 UTC, egor-bogomolov commented on running/wraped_model.py
> +    def training_step(self, batch, batch_idx):
Missing type annotations

2022-04-25 15:51 UTC, egor-bogomolov commented on running/wraped_model.py
> +    def validation_step(self, batch, batch_idx):
Missing type annotations

2022-04-25 15:51 UTC, egor-bogomolov commented on running/wraped_model.py
> +    def configure_optimizers(self):
Missing type annotations

2022-04-25 15:51 UTC, egor-bogomolov commented on running/wraped_model.py
> +    def get_loss(
Missing type annotations

2022-04-25 15:51 UTC, egor-bogomolov commented on running/util.py
> +def sparse_softmax_cross_entropy_with_logits(error_locations, loc_predictions):
Missing type annotations

2022-04-25 15:51 UTC, egor-bogomolov commented on running/util.py
> +def sparse_categorical_accuracy(y_true, y_pred):
Missing type annotations

2022-04-25 15:51 UTC, egor-bogomolov commented on running/wraped_model.py
> +        subtoken_embeddings *= torch.unsqueeze(torch.clamp(tokens, 0, 1), -1).cuda()
If you use built-in Embedding, you won't need any of it most likely

2022-04-25 15:51 UTC, egor-bogomolov commented on running/wraped_model.py
> +        # states += self.pos_enc[:states.shape[1]]
For RNN you don't need the positional encoding at all. It is needed for Transformers as they don't have a clue about positions of tokens in the sequence otherwise

2022-04-25 15:51 UTC, egor-bogomolov commented on running/wraped_model.py
> +        torch.cuda.empty_cache()
Why is it needed?

2022-04-25 15:51 UTC, egor-bogomolov commented on running/wraped_model.py
> +        self.log("val_joint_acc", acs[3], prog_bar=True)
There is `log_dict` method in lightning. Most likely it would be more convenient to return a dictionary from the `self.get_loss` function rather than parsing it this way

2022-04-25 15:51 UTC, egor-bogomolov commented on running/wraped_model.py
> +        )
Code duplicates `training_step`. Consider using the same code for training, validation, and testing steps (for examples see [shared_step here](https://github.com/JetBrains-Research/code2seq/blob/master/code2seq/model/code2seq.py))

2022-04-25 15:51 UTC, egor-bogomolov commented on running/wraped_model.py
> +        return self.validation_step(batch, batch_idx)
All the metrics will be logged with `val` prefix instead of `test`. See the comment about shared step above.

2022-04-25 15:51 UTC, egor-bogomolov commented on running/wraped_model.py
> +        self.log("val_joint_acc", acs[3], prog_bar=True)
Also, does `prog_bar=True` behave correctly when you log so much stuff one by one?

2022-04-25 15:51 UTC, egor-bogomolov commented on running/wraped_model.py
> +        # I added this because in case torch.sum(1 - is_buggy) == 0 was calculated wrong
Why not fix it right away? :slightly_smiling_face:

2022-04-25 15:51 UTC, egor-bogomolov commented on running/wraped_model.py
> +        )
You mix computations of metrics and loss here. It would be better to have separate methods and call only the one that is needed at the moment.

2022-04-25 15:51 UTC, egor-bogomolov commented on running/wraped_model.py
> +        candidate_mask = np.zeros(pointer_logits.size())
See [zeros_like](https://pytorch.org/docs/stable/generated/torch.zeros_like.html) (also exists in numpy)

2022-04-25 15:51 UTC, egor-bogomolov commented on running/wraped_model.py
> +        candidate_mask = torch.tensor(candidate_mask).cuda()
`cuda()` calls will strike back if you want to use non-cuda device. Better use `device=self.device` from Lightning

2022-04-25 15:51 UTC, egor-bogomolov commented on test/train_model_test.py
> +vocabulary_path = "/home/timav/jb/graph-code-nets/vocab.txt"
Pushing your local paths to the repository is a bad practice, this code won't run for anyone except you. Please, load the paths from config rather than hard-code and make them relative.

2022-04-25 15:51 UTC, egor-bogomolov commented on test/train_model_test.py
> +config = yaml.safe_load(open(config_path))
Config path should be passed as a parameter when calling the script

2022-04-25 15:51 UTC, egor-bogomolov commented on test/util_test.py
> +import torch
Consider turning it into real tests with pytest or unittest and add the respective line to the CI config

2022-04-28 13:16 UTC, timav566 commented on models/rnn.py
> +            hidden_size=self.hidden_dim // 2,
because of _bidirectional=True_, so the output size will be exactly _hidden_dim_

2022-04-28 19:03 UTC, timav566 commented on running/util.py
> +def positional_encoding(dim, sentence_length, dtype=torch.float32):
I decided to temporarily remove positional encoding, until I don't have a transformer model right now, but I'll work on it later. 
Btw very interesting thread about register buffer and parameter :)

2022-05-01 08:28 UTC, timav566 commented on running/wraped_model.py
> +        self.log("val_joint_acc", acs[3], prog_bar=True)
yes, it behaves correctlty but I agree with the point that it's better to use dict here.

2022-05-10 18:08 UTC, merged